@extends('portal.ticketing.layout')
@section('ticket-page-title','Dashboard')
@section('ticket-content')
@php($rp=fn($v)=>'Rp. '.number_format($v,0,',','.'))
@php($t=$totals)
<div class="section-heading"><div><div class="eyebrow">Voice of Soul · Ticketing</div><h1 class="admin-title">Setiap kursi, sebuah cerita.</h1><p class="muted">Pantau penjualan dan jangkauan konser Anda dalam satu tampilan.</p></div><a class="btn btn-primary" href="{{ route('portal.ticketing.dashboard.export',request()->only('event')) }}">Export laporan ↗</a></div>
<form method="get" class="toolbar"><label for="dashboard-event" style="margin:0">Konser</label><select name="event" id="dashboard-event"><option value="">Semua konser</option>@foreach($events as $event)<option value="{{ $event->id }}" @selected($selected?->id===$event->id)>{{ $event->title }} · {{ $event->starts_at->timezone('Asia/Jakarta')->format('d M Y') }}</option>@endforeach</select><button class="btn btn-secondary">Tampilkan</button></form>
<p class="tiny muted">Seluruh masa penjualan · Diperbarui {{ $generatedAt->format('d M Y, H:i') }} WIB · Konser dan pesanan yang dihapus tidak dihitung.</p>
<div class="performance-kpis">
@foreach([['Lunas',number_format($t['paid']).' kursi','Tiket pada pesanan lunas, termasuk tiket gratis.','#75d7b1'],['Belum Lunas',number_format($t['unpaid']).' kursi','Reservasi aktif dan pembayaran dalam proses.','#e5bb69'],['Sisa Kursi',number_format($t['remaining']).' kursi','Kapasitas yang belum terjual atau dipesan.','#a59ae8'],['Nominal Terjual',$rp($t['revenue']),'Pendapatan tiket setelah diskon, tanpa biaya pembayaran.','#e5bb69']] as [$label,$value,$note,$color])
<div class="panel performance-kpi" style="border-top:3px solid {{ $color }}"><div class="muted tiny">{{ $label }}</div><strong>{{ $value }}</strong><p class="tiny muted">{{ $note }}</p></div>@endforeach
</div>
<div class="performance-columns"><section class="panel"><div class="eyebrow">Penjualan kursi</div><h2>{{ $t['capacity']?round($t['paid']/$t['capacity']*100,1):0 }}% kapasitas terjual</h2><div class="occupancy" role="img" aria-label="{{ $t['paid'] }} lunas, {{ $t['unpaid'] }} belum lunas, {{ $t['remaining'] }} tersedia"><span style="width:{{ $t['capacity']?min(100,$t['paid']/$t['capacity']*100):0 }}%;background:#75d7b1"></span><span style="width:{{ $t['capacity']?min(100,$t['unpaid']/$t['capacity']*100):0 }}%;background:#e5bb69"></span></div><p class="tiny muted">Hijau: lunas · Emas: belum lunas · Gelap: tersedia<br>Kapasitas total: {{ number_format($t['capacity']) }} kursi</p><dl class="performance-facts"><dt>Pesanan lunas</dt><dd>{{ $t['paid_orders'] }}</dd><dt>Menunggu verifikasi</dt><dd>{{ $t['review'] }}</dd><dt>Nilai tiket belum lunas</dt><dd>{{ $rp($t['unpaid_value']) }}</dd><dt>Diskon pesanan lunas</dt><dd>{{ $rp($t['discount']) }}</dd><dt>Biaya pembayaran diterima</dt><dd>{{ $rp($t['fees']) }}</dd><dt>Total pembayaran lunas</dt><dd>{{ $rp($t['receipts']) }}</dd></dl><p class="tiny muted">Total pembayaran lunas = nominal terjual + biaya pembayaran.</p></section>
<section class="panel"><div class="eyebrow">Community spotlight</div><h2>Top 5 Referral</h2><p class="tiny muted">Berdasarkan jumlah kursi lunas. Tanpa referral tidak masuk peringkat.</p>
@forelse($referrals as $referral)<div class="referral-row"><span class="referral-rank">{{ $loop->iteration }}</span><div><strong>{{ $referral['name'] }}</strong><div class="tiny muted">{{ $referral['code'] }} · {{ $referral['orders'] }} pesanan</div></div><div style="text-align:right"><strong>{{ $referral['seats'] }} kursi</strong><div class="tiny muted">{{ $rp($referral['revenue']) }}</div></div></div>@empty<p class="muted">Belum ada penjualan lunas melalui referral.</p>@endforelse
</section></div>
<section class="panel"><h2>Kinerja per konser</h2><div class="table-responsive"><table><thead><tr><th>Konser</th><th>Lunas</th><th>Belum lunas</th><th>Sisa / kapasitas</th><th>Nominal terjual</th></tr></thead><tbody>@forelse($rows as $row)<tr><td><strong>{{ $row['event']->title }}</strong><div class="tiny muted">{{ $row['event']->starts_at->timezone('Asia/Jakarta')->format('d M Y H:i') }} WIB · {{ $row['event']->location }}</div></td><td>{{ $row['paid'] }}</td><td>{{ $row['unpaid'] }}</td><td>{{ $row['remaining'] }} / {{ $row['capacity'] }}</td><td>{{ $rp($row['revenue']) }}</td></tr>@empty<tr><td colspan="5">Belum ada konser. Data penjualan akan tampil di sini.</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><h2>Status pesanan</h2><div style="display:flex;gap:16px;flex-wrap:wrap">@forelse($statuses as $status=>$count)<span class="badge">{{ str_replace('_',' ',$status) }}: {{ $count }}</span>@empty<span class="muted">Belum ada pesanan.</span>@endforelse</div><p class="tiny muted">Reservasi kedaluwarsa, ditolak, atau dibatalkan tidak mengurangi sisa kursi. Pembayaran Midtrans yang masih diproses tetap menahan kursi.</p></section>
@endsection
@push('styles')<style>.performance-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.performance-kpi strong{display:block;font-size:clamp(1.2rem,1.8vw,1.85rem);line-height:1.3;margin:14px 0}.performance-kpi p{margin-bottom:0}.performance-columns{display:grid;grid-template-columns:1fr 1fr;gap:22px}.occupancy{height:18px;display:flex;overflow:hidden;border-radius:10px;background:var(--surface2);margin:22px 0 12px}.performance-facts{display:grid;grid-template-columns:1fr auto;gap:12px;font-size:.85rem}.performance-facts dt{color:var(--text-muted);font-weight:400}.performance-facts dd{margin:0;text-align:right}.referral-row{display:grid;grid-template-columns:32px 1fr auto;gap:12px;align-items:center;padding:15px 0;border-bottom:1px solid var(--border)}.referral-rank{width:30px;height:30px;display:grid;place-items:center;border-radius:50%;background:var(--surface2);color:var(--accent)}@media(max-width:1100px){.performance-kpis{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:700px){.performance-columns,.performance-kpis{grid-template-columns:1fr}.portal-ticketing .section-heading{flex-wrap:wrap}}</style>@endpush
